version: '3'
services:
  db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hello_pass
      POSTGRES_USER: hello_user
      POSTGRES_DB: hello
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    image: "vivalaakam/hello:0.1.11"
    command: foreground
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      PORT: 4000