FROM elixir:1.6.1
ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash
WORKDIR /app
COPY ./demo.tar.gz ./
RUN tar xfz demo.tar.gz
ENTRYPOINT ["bin/demo"]
