version: '3'
services:
  db:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: demo_prod
  web:
    image: "vivalaakam/hello:0.1.5"
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
